name: Update Tour Map

on:
  push:
    branches:
      - main

jobs:
  update_map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask app to process data and generate map
        run: python app.py

      - name: Commit and push updated map
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your Name"
          git add static/tour_map_finland.html
          git commit -m "Update tour map"
          git push
