name: Update Tour Map

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  update_map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Use the appropriate version for your code

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas folium geopy

      - name: Run map generation script
        run: python main.py # Replace with your script name

      - name: Commit and push updated map
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your Name"
          git add tour_map_finland.html
          git commit -m "Update tour map"
          git push
