name: Update Map

#on:
#  push:
#    branches:
#      - main # or the branch you want to trigger the action on
#  workflow_dispatch: # Allows manual triggering of the workflow

on:
  workflow_dispatch: # Allows manual triggering
  #schedule:
   # - cron: "0 9 * * *" # Runs daily at 9:00 a.m. UTC
  push:
    branches:
      - main # or the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Map
        env:
          TYPEFORM_API_KEY: ${{ secrets.TYPEFORM_API_KEY }}
          TYPEFORM_FORM_ID: ${{ secrets.TYPEFORM_FORM_ID }}
          TOUR_DATA_ONEDRIVE_URL: ${{ secrets.TOUR_DATA_ONEDRIVE_URL }}
          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_GRAPH_VALUE: ${{ secrets.MICROSOFT_GRAPH_VALUE }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          JAWA_MAP_API_KEY: ${{ secrets.JAWA_MAP_API_KEY }}
        run: |
          python app.py   # Adjust this to run the map generation

      - name: Commit and Push Map
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add static/map.html
          git commit -m "Update map.html"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
